apiVersion: v1
kind: Service
metadata:
  name: flask-service 
  labels:
    name: flask-service
    app: flask-app
spec: 
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005
  selector: # Paste labels from result-app-pod.yml
    name: flask-app-pods
    app: flask-app