apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: flask-app
  namespace: default
spec: 
  ports:
    - port: 6379
      targetPort: 6379
  selector: # Paste labels from redis-pod.yml
    name: redis-pod
    app: flask-app